[package]
name = "ml-kem-rs"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "FIPS 203 (draft): Module-Lattice-Based Key-Encapsulation Mechanism"
repository = "https://github.com/integritychain/ml-kem-rs"
exclude = [".idea/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
zeroize = {version = "1.6.0", features = ["zeroize_derive"]}
#typenum = {version = "1.17.0", features = ["const-generics"]}
#generic-array = {version = "1.0.0", features= ["zeroize"]}
sha3 = "0.10.8"
rand = "0.8.5"


[dev-dependencies]
rand_chacha = "0.3.1"